### ISSUE TITLE
update compose theme

### ISSUE THREAD

**Issue by Techno-Disaster** [CCExtractor/website#16]
Looks like we haven't updated our theme since [6 months](https://github.com/CCExtractor/website/blob/master/go.mod), upstream has a couple of fixes.

**Comment by cfsmp3** [comment]
> Looks like we haven't updated our theme since [6 months](https://github.com/CCExtractor/website/blob/master/go.mod), upstream has a couple of fixes.

Send a PR? :-)

**Comment by Techno-Disaster** [comment]
> > Looks like we haven't updated our theme since [6 months](https://github.com/CCExtractor/website/blob/master/go.mod), upstream has a couple of fixes.
> 
> Send a PR? :-)

Yep just added as a reminder. Need to install go and hugo tommorrow
